### ISSUE TITLE
티니핑 style 변경

### ISSUE THREAD

**Issue by SSUK-H** [Rainbow-SSAP/kkk#11]
## 작업 사항

> 기존 UI 티니핑 스타일로 수정하였습니다.

## To-do
- [x] 메인 티니핑 스타일로 UI 수정
- [x] 배경, 버튼 이미지 추가 및 상수화
- [x] 글로벌 컬러, 폰트(타이틀, 기본 폰트), 반응형 폰트 사이즈 추가
- [x] Flex 컴포넌트 width, gap css 설정 추가  

## 기타사항

> 기타 사항을 작성해주세요
