### ISSUE TITLE
결혼식 축의금 액수 결정을 위한 질문지 조회 API 개발

### ISSUE THREAD

**Issue by cipp00h** [Rainbow-SSAP/kkk#2]
## 작업 사항

> "AI 판사가 결정하는 당신의 결혼식 축의금!" 서비스를 위한 질문지 조회 API를 개발합니다. 
    사용자가 질문에 답변할 수 있도록 질문지 데이터를 조회하는 기능이 필요합니다.

## To-do
- [x] 결혼식 축의금과 관련된 질문 및 답변을 관리하기 위한 도메인 모델(Topic, Question, Answer) 설계 및 구현
- [x] 데이터 저장 및 조회를 위한 JPA Repository 인터페이스 추가
- [x] 애플리케이션 시작 시 초기 데이터를 설정하는 CommandLineRunner 구현체(DataInitializer) 추가
- [x] 설문조사 데이터를 처리하고 관리하는 서비스 계층(WeddingGiftService) 구현
- [x] 클라이언트의 HTTP 요청을 처리하는 컨트롤러(WeddingGiftController) 구현
- [x] 데이터 전송을 위한 DTO 클래스 설계 및 구현
- [x] 존재하지 않는 Topic에 대한 예외 처리 구현 

## 기타사항

> 예외 처리 부분은 추후에 수정할 예정입니다.
