### ISSUE TITLE
[FE] 프로젝트 초기 개발 환경 셋팅

### ISSUE THREAD

**Issue by SSUK-H** [Rainbow-SSAP/kkk#3]
## 작업 사항

> 프론트엔드 프로젝트 초기 환경을 셋팅 하였습니다.

## To-do
- [x] react typescript 설치 
- [x] yarn berry 설정
- [x] eslint prettier 설정
- [x] 경로 패스값 길어질 경우 대비 craco 설치 및 설정
- [x] emotion 설치 및 설정
- [x] react-query, recoil, react-router-dom 설치

## 기타사항

> 기타 사항을 작성해주세요
