### ISSUE TITLE
질문지 구현

### ISSUE THREAD

**Issue by SSUK-H** [Rainbow-SSAP/kkk#7]
## 작업 사항

> 테스트 질문지 페이지 구현하였습니다.

## To-do
- [x] 질문 메인 컴포넌트 추가 및 detail 페이지로 navigate 처리
  - 홈에 질문 메인 컴포넌트 추가
  - 버튼 클릭 시 질문 detail 페이지 navigate 처리
  - Flex 컴포넌트 alignItems을 사용하므로 수정
- [x] 라우터 코드 분리 
- [x] #11 
- [x] 기본 레이아웃 컴포넌트 추가
- [x] 많이 쓰는 패스 별칭명 추가
- [x] #12
- [x] #13
- [x] #14

## 기타사항

> 기타 사항을 작성해주세요

**Comment by SSUK-H** [comment]
Question 컴포넌트 빼고 푸시해서.. 취소하고 재푸시 합니다.
